#version: "3.8"

services:
  postgres-test:
    image: postgres:15
    container_name: pg_test
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: db_test
    #ports:
    #  - "5433:5432"
    volumes:
      - pg_test_data:/var/lib/postgresql/data

volumes:
  pg_test_data:
