global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs_app'
    static_configs:
      - targets: ['backend:5000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
 