# /.github/workflows/ci-tests.yml
name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
        working-directory: server
      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: server

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm ci
        working-directory: server
      - name: Start DB
        run: docker compose -f server/docker-compose.test.yml up -d
      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: server
