# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: [5433:5432]
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: db_test
        options: >-
          --health-cmd="pg_isready -U testuser -d db_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5433/db_test
      NODE_ENV: test
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: server

      - name: Run linter
        run: npm run lint --if-present
        working-directory: server

      - name: Run tests
        run: npm run test:ci
        working-directory: server

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          entryPoint: server
          args: >
            -Dsonar.projectKey=bbvedf_compra-venta-app
            -Dsonar.organization=bbvedf
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.javascript.lcov.reportPaths=server/coverage/lcov.info
